# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='pcdcb.proto',
  package='',
  serialized_pb='\n\x0bpcdcb.proto\"*\n\x08Instance\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x02(\t\"\xba\x01\n\x17PrecomputedDistanceData\x12\x15\n\rdata_set_name\x18\x01 \x01(\t\x12\x1c\n\x14\x64\x61ta_set_description\x18\x02 \x01(\t\x12-\n\x05\x65ntry\x18\x03 \x03(\x0b\x32\x1e.PrecomputedDistanceData.Entry\x1a;\n\x05\x45ntry\x12\x1b\n\x08instance\x18\x01 \x02(\x0b\x32\t.Instance\x12\x15\n\tdistances\x18\x02 \x03(\x01\x42\x02\x10\x01')




_INSTANCE = descriptor.Descriptor(
  name='Instance',
  full_name='Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='payload', full_name='Instance.payload', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='Instance.label', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=57,
)


_PRECOMPUTEDDISTANCEDATA_ENTRY = descriptor.Descriptor(
  name='Entry',
  full_name='PrecomputedDistanceData.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='instance', full_name='PrecomputedDistanceData.Entry.instance', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='distances', full_name='PrecomputedDistanceData.Entry.distances', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=187,
  serialized_end=246,
)

_PRECOMPUTEDDISTANCEDATA = descriptor.Descriptor(
  name='PrecomputedDistanceData',
  full_name='PrecomputedDistanceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data_set_name', full_name='PrecomputedDistanceData.data_set_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_set_description', full_name='PrecomputedDistanceData.data_set_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='entry', full_name='PrecomputedDistanceData.entry', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PRECOMPUTEDDISTANCEDATA_ENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=60,
  serialized_end=246,
)

_PRECOMPUTEDDISTANCEDATA_ENTRY.fields_by_name['instance'].message_type = _INSTANCE
_PRECOMPUTEDDISTANCEDATA_ENTRY.containing_type = _PRECOMPUTEDDISTANCEDATA;
_PRECOMPUTEDDISTANCEDATA.fields_by_name['entry'].message_type = _PRECOMPUTEDDISTANCEDATA_ENTRY
DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
DESCRIPTOR.message_types_by_name['PrecomputedDistanceData'] = _PRECOMPUTEDDISTANCEDATA

class Instance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSTANCE
  
  # @@protoc_insertion_point(class_scope:Instance)

class PrecomputedDistanceData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Entry(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PRECOMPUTEDDISTANCEDATA_ENTRY
    
    # @@protoc_insertion_point(class_scope:PrecomputedDistanceData.Entry)
  DESCRIPTOR = _PRECOMPUTEDDISTANCEDATA
  
  # @@protoc_insertion_point(class_scope:PrecomputedDistanceData)

# @@protoc_insertion_point(module_scope)
